baseURL = 'https://rhnvrm.github.io/stock-market-circulars/'
languageCode = 'en-us'
title = 'Stock Market Circulars'
theme = 'minimal'

[params]
  description = 'Regulatory circulars from NSE, BSE, and SEBI with AI-powered summaries'
  author = 'Automated Processing System'
  
[taxonomies]
  source = 'sources'
  tag = 'tags'
  severity = 'severities'
  impact = 'impacts'
  category = 'categories'
  stock = 'stocks'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 5
  [[menu.main]]
    name = 'All Circulars'
    url = '/circulars/'
    weight = 10
  [[menu.main]]
    name = 'NSE'
    url = '/circulars/nse/'
    weight = 20
  [[menu.main]]
    name = 'BSE'
    url = '/circulars/bse/'
    weight = 30
  [[menu.main]]
    name = 'SEBI'
    url = '/circulars/sebi/'
    weight = 40
  [[menu.main]]
    name = 'Tags'
    url = '/tags/'
    weight = 50
  [[menu.main]]
    name = 'Stocks'
    url = '/stocks/'
    weight = 60


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
